<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="Call_Conveyorbelts" Id="{2454d1c3-e996-4d20-af1e-35424b2544e8}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Call_Conveyorbelts]]></Declaration>
    <Implementation>
      <ST><![CDATA[(*================ Zufuehrband ================*)
instZufuehrbConveyorbelt(
	SensorInfeed:= PartPresentConveyorInfeedBegin, 
	SensorOutfeed:= Bauteil_Vorh_Zufuehrb_Aus, 
	MaximumTimeRuncontrol:= T#30S, 
	ActorInstanceIndex := 0,
	ActorInstanceName := 'FeedIn',
	HMIInterface := hmiMachineSectionInterface,
	MotorForward=> Zufuehrb_Vor, 
	RuncontrolForwardActive=> zufuehrbRunControlForwardActiv, 
	OperatingMode:= instOperatingMode.StateOperatingMode);
	
instZufuehrbConveyorbelt.MotorForward_On((PartPresentConveyorInfeedBegin OR zufuehrbRunControlForwardActiv) 
											AND NOT Bauteil_Vorh_Auslaufb_Aus AND Gabel_InPos_Mitte);
instZufuehrbConveyorbelt.Motor_Off(Bauteil_Vorh_Zufuehrb_Aus AND Bauteil_Vorh_Auslaufb_Aus);

(*================ Abholband ================*)
instAbholbConveyor(
	SensorInfeed:= Bauteil_Vorh_Zufuehrb_Aus, 
	SensorOutfeed:= Bauteil_Vorh_Auslaufb_Aus, 
	MaximumTimeRuncontrol:= T#30S,  
	ActorInstanceIndex := 1,
	ActorInstanceName := 'FeedIn Stacker Crane',
	HMIInterface := hmiMachineSectionInterface,
	MotorForward=> Abholband_Vor, 
	RuncontrolForwardActive=> abholbRunControlForwardActiv, 
	OperatingMode:= instOperatingMode.StateOperatingMode);
	
instAbholbConveyor.MotorForward_On(Bauteil_Vorh_Zufuehrb_Aus AND NOT Bauteil_Vorh_Auslaufb_Aus
									AND Gabel_InPos_Mitte);
instAbholbConveyor.Motor_Off(Bauteil_Vorh_Auslaufb_Aus);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>