<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Converters\" />
    <Folder Include="Images\" />
    <Folder Include="Models\" />
    <Folder Include="ViewModels\" />
    <Folder Include="Services\" />
    <Folder Include="Views\UserControls\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Beckhoff.TwinCAT.Ads" Version="7.0.317" />
  </ItemGroup>

</Project>
