<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="SignalmappingInput" Id="{729d2361-3cc3-4a8e-b7fa-add898f7db27}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION SignalmappingInput
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(*=============== Digitale Eingaenge ===============*)
BA_Manuel	:=	GVL.mb_Output_Coils[0];
BA_Automatik	:=	GVL.mb_Output_Coils[1];
NotAus_Hochregallager	:=	GVL.mb_Output_Coils[2];
Start_Automatik_Hochregallager	:=	GVL.mb_Output_Coils[3];
Stop_Automatik_Hochregallager	:=	GVL.mb_Output_Coils[4];
Grundstellung_Automatik_Hochregallager	:=	GVL.mb_Output_Coils[5];
Reset_Hochregallager	:=	GVL.mb_Output_Coils[6];
Quit_Hochregallager	:=	GVL.mb_Output_Coils[7];
PartPresentConveyorInfeedBegin	:=	GVL.mb_Output_Coils[9];
PartPresentConveyorInfeedEnd	:=	GVL.mb_Output_Coils[10];
PartPresentConveyorInfeedStCEnd	:=	GVL.mb_Output_Coils[11];
StackerCraneOneXAxisIsMoving	:=	GVL.mb_Output_Coils[13];
StackerCraneOneZAxisIsMoving	:=	GVL.mb_Output_Coils[14];
Gabel_InPos_Links	:=	GVL.mb_Output_Coils[15];
Gabel_InPos_Rechts	:=	GVL.mb_Output_Coils[16];
Gabel_InPos_Mitte	:=	GVL.mb_Output_Coils[17];
SensorConveyorOutfeedStackerCrane	:=	GVL.mb_Output_Coils[19];
SensorConveyorOutfeedEnd	:=	GVL.mb_Output_Coils[20];

(*=============== Analoge Eingaenge ===============*)
RFIDFeedInReceivedCommandID	:=	GVL.mb_Output_Registers[3];
RFIDFeedInStatus	:=	GVL.mb_Output_Registers[4];
RFIDFeedInReadData	:=	GVL.mb_Output_Registers[5];
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>